
#define WIDTH_PLAYER 20
#define HEIGHT_PLAYER 40

#define PADDING_LEFT_PLAYER 18
#define PADDING_TOP_PLAYER 9

// Enemies

#define WIDTH_BAT 18
#define HEIGHT_BAT 28
#define PADDING_LEFT_BAT_IDLE 7
#define PADDING_TOP_BAT_IDLE 3
#define PADDING_LEFT_BAT_ATTACK 28
#define PADDING_TOP_BAT_ATTACK 26

#define WIDTH_RAT 56
#define HEIGHT_RAT 24
#define PADDING_LEFT_RAT 19
#define PADDING_TOP_RAT 16

#define WIDTH_DIABLO 25
#define HEIGHT_DIABLO 43
#define PADDING_LEFT_DIABLO 16
#define PADDING_TOP_DIABLO 11

// Items
#define WIDTH_COIN 28
#define HEIGHT_COIN 28
#define PADDING_LEFT_COIN 0
#define PADDING_TOP_COIN 0

#define WIDTH_GEM 26
#define HEIGHT_GEM 26
#define PADDING_LEFT_GEM 6
#define PADDING_TOP_GEM 5

#define WIDTH_CARROT 13
#define HEIGHT_CARROT 30
#define PADDING_LEFT_CARROT 11
#define PADDING_TOP_CARROT 4

#define WIDTH_AMMO 24
#define HEIGHT_AMMO 24
#define PADDING_LEFT_AMMO 0
#define PADDING_TOP_AMMO 0

// Projectile
#define WIDTH_PROJECTILE 3
#define HEIGHT_PROJECTILE 3
#define PADDING_LEFT_PROJECTILE 16
#define PADDING_TOP_PROJECTILE 4

