ObjectPlayer:
  health: 10
  speed_walk: 15
  speed_run: 20
  speed_intoxicated: 2
  speed_jump: 10
  speed_fall: 15

ObjectProjectile:
  damage_p1: 1
  damage_p2: 2
  damage_p3: 3
  damage_p4: 4
  speed_p1: 11
  speed_p2: 12
  speed_p3: 13
  speed_p4: 14

ObjectCollected:
  pts_diamante: 20
  pts_moneda: 10
  pts_municion: 3
  pts_zanahoria: 2
  pts_zanahoria_podrida: 0
  proba_podrida: 20 # Entre 0 y 100

EnemyBat:
  damage: 1
  health: 4
  speed: 15
  points: 1
  respawn_time: 10 # Segundos
  dropping_ammo_chance: 10
  movement_range: 15

EnemyDiablo:
  damage: 1
  health: 4
  speed: 15
  points: 1
  respawn_time: 10
  dropping_ammo_chance: 10
  movement_range: 15

EnemyRat:
  damage: 1
  health: 4
  speed: 15
  points: 1
  respawn_time: 10
  dropping_ammo_chance: 10
  movement_range: 15

Game:
  time: 250
